export {default as LivePlugin} from './live'
export {default as TriggerLive} from './trigger'
export {default as FishLive} from './fish'
export {default as BiliBili} from './bilibili'
export {default as DouYin} from './douyin'
